### ISSUE TITLE
Can't Launch

### ISSUE THREAD

**Issue by retrospectsecurity** [ZebusJesus/Meshtastic-PyGUI#11]
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/dist-packages/meshtastic_pygui/__main__.py", line 19, in <module>
    from map3 import mapNODE
ModuleNotFoundError: No module named 'map3'

**Comment by wolfcry0** [comment]
Same issue here, I haven't had any luck finding what module map3 is to do a manual install.

**Comment by arankwende** [comment]
Hi guys, I had the exact same issue.
At first, it seems the module map3.py is on the same folder __main__.py but it isn't being found, so I added a . in front of the import sequence but when I did that, another dependency was missing( from mpl_toolkits.basemap import Basemap) used by map3.py and I didn't manage to find it on pip so, what I did in order to be able to execute the app for now (until devs can point us into the right direction) is comment lines 19 (the module import) and the only place where the module is used, lines 579, 580, 581, 582 and 583.
After that the application launched and I managed to connect to my TTGO through USB.

**Comment by mkinney** [comment]
Can you try the latest version?

```
pip3 install Meshtastic-PyGUI
meshtastic_pygui
```

**Comment by spydercs** [comment]
I tried the latest version and I get a different message:

user@linuxbox:~$ meshtastic_pygui
Traceback (most recent call last):
  File "/home/user/.local/bin/meshtastic_pygui", line 5, in <module>
    from meshtastic_pygui.__main__ import main
  File "/home/user/.local/lib/python3.9/site-packages/meshtastic_pygui/__main__.py", line 11, in <module>
    import PySimpleGUI as sg
  File "/home/user/.local/lib/python3.9/site-packages/PySimpleGUI/__init__.py", line 2, in <module>
    from .PySimpleGUI import *
  File "/home/user/.local/lib/python3.9/site-packages/PySimpleGUI/PySimpleGUI.py", line 127, in <module>
    import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'
